fixed issue where large image would render in different env #80
fossasia/visdom pull request #891
Opened 2022-12-02 11:39 UTC by Aryanamish

Updated the backend to send the **environment ID** with the render information.

Updated the Front End to ignore the incoming window when it is not in the currently selected environment

## Motivation and Context
issue #80 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactor or cleanup (changes to existing code for improved readability or performance)

## Checklist:

- [ ] I adapted the version number under `py/visdom/VERSION` according to [Semantic Versioning](https://semver.org/)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-12-02 21:51 UTC, JackUrb approved these changes
A nice simple fix to a longstanding problem. Thanks for taking this on @Aryanamish!

2022-12-02 22:09 UTC, JackUrb commented
Hm I'm unsure why the tests are failing here, it may be a good idea to rebase then regen the minified frontend.

2022-12-05 19:10 UTC, da-h commented
Great bugfix!

As a side-note:
- In the "Files changed"-Tab above, Github shows the Linter-Error positions. (I just found out that this feature exists :sweat_smile: ).
- The failing Visual Regression Test leave me a bit puzzled. I would also guess that rebasing should solve these. Otherwise there are possibly some unexpected side-effects? I'll look into this if it's failing again after rebase.

2022-12-06 06:14 UTC, Aryanamish commented
I fixed the linting error

2022-12-06 17:38 UTC, da-h commented
**The failing of the functional test seems legitimate to me**:
This PR in its current form does not work for forked environments.

Reason is that the state of each window does not yet adapt to the new `eid` when forking. (See https://github.com/fossasia/visdom/blob/master/py/visdom/server/handlers/web_handlers.py#L472).

The Python Linter-Error can be fixed easily.

---

**Regarding the other failing tests**:
1. What I do not understand, yet, is why the visual regression tests are failing. The error says that the visual test-images do not match, which i cannot confirm from looking shortly into it. I'll look into it later/tomorrow in more detail.
2. The Javascript Linter can be ignored for now. I have a solution at hand, fixing all these errors, but need just a bit more time to finish the PR conscientious.

Best,
*da-h*

2022-12-06 18:09 UTC, da-h commented
**I've checked the visual regression test, which is legitimately failing as well**:

For instance the end-state for the test `compare_plot_line_multiple` looks like this:
![Compare with compare-view screenshots -- Compare screenshot for plot_line_multiple (failed)](https://user-images.githubusercontent.com/19650074/205988239-1eaf82fd-1aa2-4195-8233-8f56caa332f3.png)

but should contain this compare plot:
![compare_plot_line_multiple](https://user-images.githubusercontent.com/19650074/205988383-5682d592-6599-4d0d-af3b-82d9ad0a3c61.png)

2023-03-20 13:42 UTC, JackUrb requested changes
Moving to a change request based on @da-h's analysis.

2026-02-22 08:41 UTC, mariobehling commented
Thanks for your contribution! A small process note.

We have automatic Copilot PR reviews enabled on this repository. These reviews are only triggered if the contributor has GitHub Copilot enabled and an active license on their own account.

Please enable Copilot in your GitHub settings if you have access. In many regions, free licenses are available through educational institutions or developer programs. Enabling Copilot helps us speed up the auto review process and reduces manual review overhead for the core team.

The team will review your PR. Thank you for your contribution and cooperation.

2026-02-22 08:41 UTC, mariobehling requested changes
@Aryanamish Thank you for your contribution. Please resolve conflicts. Thanks!

2026-05-14 20:07 UTC, ArnavBallinCode reviewed
Thanks for the contribution and for working on this long-standing issue.

We are closing this PR in favor of #1267, which provides a more focused and up-to-date implementation of the cross-environment rendering fix.

While this PR introduced the initial idea of attaching environment metadata to window updates, there are still unresolved issues around environment forking behavior, stale window state handling, and compare-view regressions that were identified during review and testing.

In addition:

- The branch is significantly out of date and has unresolved merge conflicts
- Multiple functional and visual regression issues were reported during review
- The newer PR (#1267) addresses the same root issue with a more scoped approach based on environment-aware message validation
- #1267 also incorporates feedback gathered during the review cycle of this PR

Closing this PR to consolidate review and implementation efforts into the actively maintained replacement PR. Thanks again for the original contribution and investigation in

2026-05-14 20:07 UTC, closed without merging